### ISSUE TITLE
Conflicts with another subnet

### ISSUE THREAD

**Issue by Mahaswami** [waterbear-cloud/paco#40]
**Describe the bug**
When running this command:  "paco provision netenv.spaco.prod" Stack creation failing and throwing below error.

ERROR: 
Stack:         NE-spaco-prod-Net-private-Segments
Template:      /home/sample-paco/.paco-work/build/templates/prod/us-east-1/NE-spaco-prod-Net-private-Segments.yaml
Stack Status:  StackStatus.CREATE_FAILED
Status Reasons:
LogicalId             Status Reason
---------             -------------
NE-spaco-prod-Net-pr  The following resource(s) failed to create: [NACLAZ1, SubnetAZ2, RouteTableAZ2, NACLAZ3, RouteTableAZ1, NACLAZ2, RouteTableAZ3, SubnetAZ1, SubnetAZ3]. 
SubnetAZ3             The CIDR '10.4.3.0/24' conflicts with another subnet (Service: AmazonEC2; Status Code: 400; Error Code: InvalidSubnet.Conflict; Request ID: ba58cafc-4299-4d6b-bca0-d0801c6a249b)
RouteTableAZ3         Resource creation cancelled
NACLAZ3               Resource creation cancelled
NACLAZ2               Resource creation cancelled
RouteTableAZ2         Resource creation cancelled
NACLAZ1               Resource creation cancelled
RouteTableAZ1         Resource creation cancelled
SubnetAZ2             The CIDR '10.4.2.0/24' conflicts with another subnet (Service: AmazonEC2; Status Code: 400; Error Code: InvalidSubnet.Conflict; Request ID: 2e66b08a-ce95-4936-9d3b-2017ecabe0a6)
SubnetAZ1             The CIDR '10.4.1.0/24' conflicts with another subnet (Service: AmazonEC2; Status Code: 400; Error Code: InvalidSubnet.Conflict; Request ID: fc62b583-a020-4b16-b0d0-811d98e2cfc9)

**Comment by kteague** [comment]
Looks like there are conflicting CIDR settings for the subnets. Paco does not attempt to validate against CIDR overlap.

Does your netenv/spaco.yaml file have several segments in them with the same CIDRs?

For example, if you have a public and a private segments and they both use 10.4.2.0/10.4.1.0/10.4.3.0?

```
environments:
  prod:
    us-west-2:
      enabled: true
    default:
      applications:
      network:
        aws_account: paco.ref accounts.prod
        vpc:
          cidr: 10.4.0.0/16
          segments:
            public:
              az1_cidr: 10.4.1.0/24
              az2_cidr: 10.4.2.0/24
              az3_cidr: 10.4.3.0/24
              internet_access: true
            private:
              az1_cidr: 10.4.4.0/24
              az2_cidr: 10.4.5.0/24
              az3_cidr: 10.4.6.0/24
              internet_access: false
```

If you are still stuck can you share your netenv/spaco.yaml file?
